### ISSUE TITLE
Multiple errors with 5.5.2p2

### ISSUE THREAD

**Issue by noorbeast** [sketchfab/Unity-glTF-Exporter#14]
Assets/Sketchfab Exporter/ExporterSKFB.cs(2,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/ExporterSKFB.cs Line: 2)

Assets/Sketchfab Exporter/ExporterSKFB.cs(9,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/ExporterSKFB.cs Line: 9)

Assets/Sketchfab Exporter/GlTF_Animation.cs(4,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/GlTF_Animation.cs Line: 4)

Assets/Sketchfab Exporter/GlTF_ExporterWindow.cs(4,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/GlTF_ExporterWindow.cs Line: 4)

Assets/Sketchfab Exporter/GlTF_Parameters.cs(5,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/GlTF_Parameters.cs Line: 5)

Assets/Sketchfab Exporter/SceneToGlTFWiz.cs(8,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/SceneToGlTFWiz.cs Line: 8)

Assets/Sketchfab Exporter/ExporterSKFB.cs(22,29): error CS0246: The type or namespace name `EditorWindow' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/ExporterSKFB.cs Line: 22)

Assets/Sketchfab Exporter/GlTF_ExporterWindow.cs(8,35): error CS0246: The type or namespace name `EditorWindow' could not be found. Are you missing an assembly reference?
 
(Filename: Assets/Sketchfab Exporter/GlTF_ExporterWindow.cs Line: 8)

**Comment by AurL** [comment]
I didn't know that UnityEditor lib can be missing in some setups, but this lib is definitely required by the exporter to work. It uses a few Editor objects and functions.

Are you using it in a build ? 
Note that the next version (that should come in a few hours now) will fix the issue where build process is broken because of Editor Scripts.

Thanks,

**Comment by AurL** [comment]
[Version 2.0.5](https://github.com/sketchfab/Unity-glTF-Exporter/releases/tag/2.0.5) should fix these errors when building the unity project.
If you get these errors inside the editor, it's a case that the exporter doesn't handle. 
Note that in a few versions, the exporter should be embeddable in a build.

Thanks for reporting!
