### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by vsantosu** [sketchfab/Unity-glTF-Exporter#26]
Hello there,

Which licence is planned for this repo?

Thanks!

**Comment by cedricpinson** [comment]
It's a fork from https://github.com/tparisi/Unity-glTF-Exporter so we dont plan to change the license

**Comment by vsantosu** [comment]
Hello @cedricpinson,

Just to clarify, the previous repo(tparisi/Unity-glTF-Exporter) has a MIT license. Meaning this repo must include the License and Copyright. A repo without license mean proprietary, I'm missing something?  I'm asking because I'm planning to try to fix some bugs and do PR, but not sure about the current licensing since I don't see it in the master branch.

**Comment by cedricpinson** [comment]
No you are right, I dont know why it's not here but anyway we will fix this quickly

**Comment by AurL** [comment]
Hi @vsantosu ,

It seems that the LICENSE has been deleted accidentaly, but it's obviously the same as the main repo.
I just pushed it, problem solved.

Thanks!

**Comment by vsantosu** [comment]
Thanks to you guys!! I will check out some problems I have seen with the export specs, will open another issue later.
